[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = []
description = "TODO"
documentation = "https://docs.rs/vec1"
keywords = ["vec", "min", "length", "1"]
license = "MIT OR Apache-2.0"
name = "vec1"
readme = "./README.md"
repository = "https://github.com/1aim/mail-codec/"
version = "0.1.0"

[dependencies]

