[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = ["data-structures"]
description = "a std Vec wrapper assuring that it has at least 1 element"
documentation = "https://docs.rs/vec1"
keywords = ["vec", "min", "length", "1"]
license = "MIT OR Apache-2.0"
name = "vec1"
readme = "./README.md"
repository = "https://github.com/1aim/vec1/"
version = "1.0.1"

[dependencies]

